### ISSUE TITLE
vue-foundation with express

### ISSUE THREAD

**Issue by besnikh** [vue-foundation/vue-foundation#12]
Hi,
I cloned this repo for my Foundation project, and now after I am ready to start the server side coding I don't have any idea where to start :( It's just so different from all boilerplates I've been working with. 

Can someone give me a hand where would my server.js file be, or how should I use it now with Vue and webpack... 

Please note I'm noob with Vue, but I love it and also I don't have so much experience with Webpack

Thnx in advance

**Comment by grantcarthew** [comment]
Hi @besnikh 

Start by typing `npm run dev` into the console when you are in the project or template directory.

Here is where the server.js file is: https://github.com/hal0gen/vue-foundation/blob/master/build/dev-server.js

**Comment by besnikh** [comment]
Hi @grantcarthew 

I already built my front end by runing npm run dev, but now I don't know where to start describing app.use, routes etc.. 
I already built my front with Foundation, that's why I wanted to use your boilerplate, but I don't know how to proceed now. 

I want to make my API folder now, and on that API folder I want to be able to write routes, rules etc.. 

Can you help me out with this ? It's maybe to noob question, but damn'it :(

**Comment by besnikh** [comment]
@grantcarthew 

I see that build/dev-server.js is like the server.js for the express, but now how should I proceed to create a new folder API, and then add my routes, rules and other stuff than should I import that file to dev-server.js or how should I proceed ?

**Comment by grantcarthew** [comment]
Ah, I see your problem @besnikh.

Vue.js is part of a Single Page App framework. These types of webapps typically consist of static pages with js/css/jpg resources. When the application is complete you run the `npm run build` script that will produce the static site for you. Your web API or REST API needs to be built in a seperate project.

DO NOT use the dev-server.js file to build an API.

Try this: https://scotch.io/tutorials/build-a-restful-api-using-node-and-express-4

**Comment by hal0gen** [comment]
Hi @besnikh, I totally agree with @grantcarthew , you don't want to try hacking the dev server! :)  Once you're done building your app, you can use Express to serve it if you want, although I really don't see the point, Apache or Nginx are probably more suitable. In that case, watch out for [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS): if your server and your client app are on different URLs you'll need to add some CORS policy to your Express app otherwise your browser will block all requests.
