### ISSUE TITLE
Move to organization

### ISSUE THREAD

**Issue by hal0gen** [vue-foundation/vue-foundation#14]
I see this repo is getting some interest in the last weeks, very happy about that. However, I haven't got the time to work properly on that in the last month, and that will probably last for a few more weeks. Instead, @grantcarthew has been actively contributing to that. I definitely want to get back to this ASAP, but in the meanwhile I think we should consider moving the repo to an organization, @grantcarthew I sent you an invitation. I am also very intrigued by the Foundation Building blocks, I think it would be nice to create a separate repo which is just a library of plug and play Vue components. Also, as Foundation is becoming truly modular and supporting webpack, when 6.4 is out I think a nearly complete rewrite of this repo will be necessary. #13 I guess the organization can also help in getting other people aboard, thoughts on that?

**Comment by grantcarthew** [comment]
Hi @hal0gen.

I haven't used Orgs much so I just did a catchup on Orgs here: https://help.github.com/articles/differences-between-user-and-organization-accounts/

Following are the important details from that link for anyone reading through:

## Organizations

Organizations are shared accounts where groups of people can collaborate across many projects at once. Owners and administrators can manage member access to the organization's data and projects with sophisticated security and administrative features.

## Organizations include:

*   A free plan with unlimited collaborators on unlimited public repositories
*   The option to upgrade to paid plans with unlimited private repositories, sophisticated user authentication and management, 24/5 support, and a service level agreement for uptime availability
*   Team-based repository access permissions
*   Unlimited owners, administrators, and collaborators using teams
*   The ability for organization owners to view members' two-factor authentication (2FA) status
*   The option to require all organization members to use two-factor authentication

Sounds like a good move to me. Especially if you are planning the component modules.

**Comment by hal0gen** [comment]
@grantcarthew glad you agree! I started looking into the actual transfer, shouldn't be too hard. I still have to fully figure out how to move the GitHub Pages website associated with the repo without breaking links...

**Comment by hal0gen** [comment]
Done! I updated the link in the repo description...
