### ISSUE TITLE
Slider does not update on move

### ISSUE THREAD

**Issue by kevinpt** [vue-foundation/vue-foundation#2]
The slider control does not update the dataValue state on changes. It seems that the callback for "moved.zf.slider" is not firing.

https://hal0gen.github.io/vue-foundation/#/slider

**Comment by grantcarthew** [comment]
It's working fine for me @kevinpt 

I have some slight changes though as follows:

In `build/utils.js` to add scss variables and references:

```js

  let sassOptions = {
    indentedSyntax: true
  }
  let scssOptions = {
    includePaths: [
      '~src/styles'
    ],
    data: '@import "~src/styles/app";'
  }

  // http://vuejs.github.io/vue-loader/en/configurations/extract-css.html
  return {
    css: generateLoaders(),
    postcss: generateLoaders(),
    less: generateLoaders('less'),
    sass: generateLoaders('sass', sassOptions),
    //  Make custom SASS available to all components https://github.com/webpack-contrib/sass-loader
    scss: generateLoaders('sass', scssOptions),
    stylus: generateLoaders('stylus'),
    styl: generateLoaders('stylus')
  }


```

Here is what the `src/main.js` looks like:

```js

// The Vue build version to load with the `import` command
// (runtime-only or standalone) has been set in webpack.base.conf with an alias.
import Vue from 'vue'
import App from './App'
import router from './router'
import jQuery from 'jquery'
window.jQuery = window.$ = jQuery

require('motion-ui')
require('what-input')
require('foundation-sites')

/* eslint-disable no-new */
new Vue({
  el: '#app',
  router,
  template: '<App/>',
  components: { App }
})


```

And `styles/app.scss`:

```js

// This file gets imported in every component by the scss cssLoader
// It is referenced by the sass compiler within build/utils.js
// https://github.com/vuejs/vue-loader/issues/328

// Load Foundation
@import './settings';
@import '~foundation-sites/scss/foundation';

// Load scss variables and settings
// These are your own custom variables in scss files under styles.
@import './layout';
@import './palette';
@import './colours';


```

**Comment by hal0gen** [comment]
I confirm it's not working on Chrome 56 on Android 6.0. @kevinpt what browser are you using? I'll look into that

**Comment by hal0gen** [comment]
@grantcarthew that's good, how about a pull request?

**Comment by grantcarthew** [comment]
It has some issues at the moment. I don't know if this project has them also. The main one is that wepback/node-sass duplicate the `<script>` elements for foundation. I have 14 copies of foundation loading into the page. It only happens in `dev-server` dev mode, so I'm not too fussed.

**Comment by grantcarthew** [comment]
ok, let me try out your template now. I was just using it as a reference.

**Comment by grantcarthew** [comment]
Ok, back to my own work now. Try it out: https://github.com/hal0gen/vue-foundation/pull/3

**Comment by kevinpt** [comment]
This fails for me on Chrome 56, IE10, and an old Firefox 46 all under Win7 64-bit.

**Comment by grantcarthew** [comment]
Well @kevinpt, I've done my part, your turn to shine?
Is it working on anything even the latest browsers?
Why would it work for me and not for you?

**Comment by hal0gen** [comment]
@grantcarthew I'll check the sass part. I also had some repetition issues, but I reckon it's ok now. Anyway, I can also reproduce the bug on multiple browsers / OS

**Comment by hal0gen** [comment]
436866f fixes it. jQuery was not properly imported.
