### ISSUE TITLE
Path in production build config

### ISSUE THREAD

**Issue by dbig** [vue-foundation/vue-foundation#21]
Happy to have discovered this!  I'm somewhat familiar with Foundation, but learning Vue and Webpack.

Just wanted to let you know that your production build config assumes the project folder has the same name as the repository.

`assetsPublicPath: '/vue-foundation/',`

Setting it to '/' was necessary as I have a unique project folder name.

Thanks very much for sharing!

**Comment by grantcarthew** [comment]
Thanks for that. I changed the setting to `/` however I just did it in the browser. It's not tested. Leave this open until it has been tested.

**Comment by grantcarthew** [comment]
Closing due to Foundation 6.4 upgrade and v2.0.
