### ISSUE TITLE
How to run dev on https?

### ISSUE THREAD

**Issue by Gotterbild** [vue-foundation/vue-foundation#27]
First of all, thanks for saving a lot of time.

I need to run dev on **https**. How do I do that?

Tried:
1. **dev-server.js**
   `var uri = 'https://localhost:' + port`

   But obvously it just opens browser on `https://localhost:8080` and not making server serve via https.

2. **webpack-dev-conf.js**
   ``` javascript
      module.exports = merge(baseWebpackConfig, {
     ***
     plugins: [
      ***
      new webpack.LoaderOptionsPlugin({
         options: {
           https: true,
           secure: true,
         }
       })
   ```
   Doesn't do anything.

3. **/config/index.js**
   ``` javascript
   module.exports = {
     ***
     dev: {
       https: true,
       secure: true,
       ***
   ```
   Doesn't do anything.

4. Tried to use `proxyTable` in **/config/index.js** to proxy from https to http. But it didn't work as you need to listen to https to proxy from that. Kinda the same as number 1 of this list. 

I've read all the docs on https of [NodeJS](https://nodejs.org/api/https.html), of [webpack-dev-server](https://webpack.github.io/docs/webpack-dev-server.html#webpack-dev-server-cli), [Vue's webpack docs](http://vuejs-templates.github.io/webpack/) and didn't figured out the answer.

I've even tried to proxy with apache2, but it didn't work and I couldn't find out if it is me writting something wrong in config files (or in wrong files) or if it is a conflict between apache2 and node.

Any help or ideas would be much appreciated.

**Comment by grantcarthew** [comment]
I haven't used it with the template myself @Gotterbild however I think you are barking up the wrong tree. You want to have a look at Express: http://expressjs.com/en/api.html#app.listen

Edit the `dev-server.js` to support https as is explained in the above link.
https://github.com/vue-foundation/vue-foundation/blob/master/build/dev-server.js

**Comment by Gotterbild** [comment]
@grantcarthew Thanks for the links.

**Comment by grantcarthew** [comment]
Closing for now. Open if you have more questions.
