### ISSUE TITLE
uglify fails because vendor.[hash].js output file still has es6 syntax after npm run build

### ISSUE THREAD

**Issue by thall1961** [vue-foundation/vue-foundation#29]
Not sure why there's still es6 syntax in the output file after npm run build.  webpack.prod.conf.js clearly pulls in webpack.base.conf.js and merges which includes babel for *.js files...

Happens after fresh clone, yarn install, npm start, npm run build.

Error I see (on Windows 10):

ERROR in static/js/vendor.1d7735529c6a703cb5af.js from UglifyJs
Unexpected character '`' [./~/foundation-sites/js/foundation.util.core.js:24,0][static/js/vendor.1d7735529c6a703cb5af.js:10294,124]

line 10294:

`  return Math.round((Math.pow(36, length + 1) - Math.random() * Math.pow(36, length))).toString(36).slice(1) + (namespace ? `-${namespace}` : '');`

Containing function:

`function GetYoDigits(length, namespace){
  length = length || 6;
  return Math.round((Math.pow(36, length + 1) - Math.random() * Math.pow(36, length))).toString(36).slice(1) + (namespace ? `-${namespace}` : '');
}`

*sorry about code formatting

**Comment by grantcarthew** [comment]
Hi @thall1961,

I just had a quick look and there is no Pollyfill for this: https://babeljs.io/docs/plugins/transform-es2015-template-literals/
It should transform without a problem.

I don't have time to test at the moment. Will if I get the chance.

**Comment by peerbolte** [comment]
I have the same issue, maybe this thread explains what's going on. Unsure how to fix it though:

https://github.com/zurb/foundation-sites/issues/10161

**Comment by peerbolte** [comment]
Ok, so I did some digging. Apparently Foundation core is not transpiled to ES5, which for other libraries is pretty much standard. See this comment why it isn't transpiled: https://github.com/zurb/foundation-sites/issues/10275#issuecomment-312324673

A temporary fix is to directly import the scripts without using require in main.js.

In main.js comment out:

```
// require('motion-ui');
// require('what-input');
// require('foundation-sites');
```
and add the following imports

```
import 'script-loader!jquery/dist/jquery.min';
import 'script-loader!motion-ui/dist/motion-ui.min';
import 'script-loader!what-input/dist/what-input.min';
import 'script-loader!foundation-sites/dist/js/foundation.min';
```

This is probably not the cleanest way to solve this. But it get's the job done for now.

**Comment by grantcarthew** [comment]
Is this still a problem after the Foundation 6.4 upgrade?

**Comment by lopezi** [comment]
yes, i just got:
`ERROR in static/js/vendor.b86ce69ea9f8127f90fb.js from UglifyJs
Unexpected token: name (Equalizer) [./node_modules/foundation-sites/js/foundation.equalizer.js:16,0][static/js/vendor.b86ce69ea9f8127f90fb.js:29,6]
`

**Comment by grantcarthew** [comment]
I don't think the recent change I made will fix this issue however if someone can try the new master branch out please?

I have change the foundation import significantly: https://github.com/vue-foundation/vue-foundation/blob/master/src/foundation.js

**Comment by grantcarthew** [comment]
I've pushed what I believe is a fix however I have not tested it. Please test out the latest master @lopezi.

Here is the fix: https://github.com/vue-foundation/vue-foundation/blob/7c30d6a1745dcf7e70e7f0ed4a26cadb981f2b26/build/webpack.base.conf.js#L50

I just told babel to transpile the foundation-sites js files.

**Comment by lopezi** [comment]
shall we expect a dist folder?

**Comment by chrisroselli** [comment]
`Build` is now working for me. Static files live in `docs` folder. Thanks @grantcarthew

**Comment by lopezi** [comment]
same here, Thanks @grantcarthew and @chrisroselli

**Comment by grantcarthew** [comment]
Great!
