### ISSUE TITLE
Error on npm start

### ISSUE THREAD

**Issue by didinkaj** [vue-foundation/vue-foundation#30]
Errors:
  23  http://eslint.org/docs/rules/linebreak-style

 @ ./src/router/index.js 13:0-45
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

 error  in ./src/components/Tabs.vue

  ✘  http://eslint.org/docs/rules/linebreak-style  Expected linebreaks to be 'LF' but found 'CRLF'
  C:\Users\johnson\Desktop\vue\storemanagement\vuefoundation\vue-foundation\src\components\Tabs.vue:26:9
  /* HTML */
           ^

**Comment by grantcarthew** [comment]
I'm not working on it at the moment @didinkaj. Are you happy to send a PR?

**Comment by grantcarthew** [comment]
Closing due to Foundation 6.4 upgrade and v2.0. If you still see this issue please re-open.
