### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by simonjcarr** [vue-foundation/vue-foundation#36]
After cloning and npm install, I got an error when running npm start saying that my node installation may be outdated. I upgraded node and now npm start completes but I get 37 eslint line break errors. I am running this on windows (Could that be a problem).

Any way even with these errors the server seems to start and opens the browser, but all I get in the browser window is 

Cannot GET /

**Comment by grantcarthew** [comment]
Post the console output @simonjcarr.

**Comment by mikegking** [comment]
I'm seeing the same issue on windows.  Lots of these:
http://eslint.org/docs/rules/linebreak-style  Expected linebreaks to be 'LF' but found 'CRLF'
  src\router\index.js:37:4
  });
and then in the browser (IE and Chrome) all I see is a "Cannot GET /" message on the page.

VSCode is complaining about the same eslint issue too.

**Comment by mikegking** [comment]
Ok found it - for anyone else finding this, I used a solution as per here: https://github.com/wellyshen/react-cool-starter/issues/72

Try `git config --global core.autocrlf false` at the command line and re-clone the project.

**Comment by mgyatso** [comment]
[mikegking](https://github.com/mikegking)'s fix did the trick.

**Comment by grantcarthew** [comment]
Good to here. Nice work guys.
