### ISSUE TITLE
Nice, and almost works

### ISSUE THREAD

**Issue by pimboden** [vue-foundation/vue-foundation#37]
I really like it, and it really helped.. There is a problem with Internet explorer (yes I also hate that browser) An error is thrown when starting up the off-canvas

**Comment by grantcarthew** [comment]
Hi @pimboden. I have not used it against IE. Don't plan on it either. Not sure about @hal0gen.
If you are so inclined, please fault find it and give feedback. I will not be trying it out.

**Comment by pimboden** [comment]
@grantcarthew I think I'll ignore IE too... all the other browsers work... so close this "issue".

**Comment by grantcarthew** [comment]
haha, poor IE. Sitting in the corner all alone. Crying into his beer.

**Comment by thebrownfox** [comment]
Hey guys, have you found something out? All I get is:
```
[Vue warn]: Error in mounted hook: "TypeError: Invalid calling object"

found in

---> <App> at src/App.vue
```
