### ISSUE TITLE
Contributions: What's next for this library?

### ISSUE THREAD

**Issue by gwenf** [vue-foundation/vue-foundation#44]
@grantcarthew @alonisser @hal0gen 
I want to make some updates to this library and also turn it into a Vue-CLI plugin. Is there anyone here who is still willing to maintain this project? If not, I would appreciate it if you handed over the organization to a new maintainer.
Thanks.

**Comment by grantcarthew** [comment]
Hi @qwenf.
I don't know if this project is still valid anymore. I haven't touched it in ages.
Let me see what permissions I have on the repo.

**Comment by grantcarthew** [comment]
Looks like I had permissions to add you.
https://github.com/vue-foundation/vue-foundation/invitations
Go nuts.
