### ISSUE TITLE
Destory does not work

### ISSUE THREAD

**Issue by grantcarthew** [vue-foundation/vue-foundation#6]
Hi @hal0gen 
I started working on the template and found errors in the console.

After a little research found out the `foundation('destroy')` function will not work on `this.$el` unless that is the element foundation is mounting.

I tested the destroy on the tool-tip page with a selector `$('.has-tip').foundation('destroy')` and it worked.

I think there would need to be a tree traversal using [jQuery.find()](https://api.jquery.com/find/). I'm not sure this is a good idea though.

For now I have removed the destroy hook from the mixin. Everything still works.

**Comment by hal0gen** [comment]
Yes, I can reproduce and I get the same error if I use the `beforeDestroy()` hook. I can see it works without, I am just worried this might leave instances/listeners around, which could be a problem in a real web app. I am also not really fond of jQuery DOM traversal (or jQuery in general, but that's the price to pay for Foundation).

**Comment by grantcarthew** [comment]
I don't have a solution yet. It seems strange that `.foundation()` will initialize all elements with the required tags and yet `.foundation('destroy')` does not.

Unless the destroy is working like you would expect however the Vuejs $el is not in the right state. I also tried the beforeDestroy hook thinking that would be the issue.

Could test with a setTimeout() in the mounted hook. In the callback call destroy just to see if it works.
I'm away from my workstation. Will try that.

**Comment by grantcarthew** [comment]
Found some time to work on my personal project. Destroy does not seem to cause errors in my project. Don't know why yet.

**Comment by hal0gen** [comment]
This is weird... I think this can stay open for now, if you spot the reason why yours works let me know!

**Comment by grantcarthew** [comment]
No longer relevant since removing the mixin.
