### ISSUE TITLE
Official Template - Integrate the option to add Foundation node package

### ISSUE THREAD

**Issue by grantcarthew** [vue-foundation/vue-foundation#7]
https://github.com/vuejs-templates/webpack/pull/606

**Comment by hal0gen** [comment]
@grantcarthew I suspected Vue people did not want something like Foundation to be included in an official template, it's too specific (just look at the [vue-resource](https://github.com/pagekit/vue-resource) story). The feedback so far goes in this direction...

**Comment by grantcarthew** [comment]
Agreed. They didn't even add vuex.
