### ISSUE TITLE
Remove the foundation.js mixin

### ISSUE THREAD

**Issue by grantcarthew** [vue-foundation/vue-foundation#9]
Why not explicitly mount each plugin?

I'm using this syntax in my project:

```js

  mounted () {
       this.signInModal = new Foundation.Reveal($('#signin-modal'))
    },
...
   beforeDestroy () {
      this.signInModal.$element.foundation('destroy')
   }

```

More explicit with less magic. No tree traversal to find the element again either.

**Comment by grantcarthew** [comment]
@hal0gen 

Please check this out Tommaso. I have removed the mixin from the accordion and added `mounted()` and `destroyed()` to init the plugin.

https://github.com/vue-foundation/vue-foundation/blob/FoundationJS/src/components/Accordion.vue

It is more verbose however gives more control and removes the magic and destroy issue.

**Comment by hal0gen** [comment]
I like it. My love for Vue mixins didn't last too long... It's true they let you save a few lines but they easily bite you as soon as your component size grows (especially when you forget they are there and are trying to spot a bug in the component code, true story). In theory, the same would also apply to the sass loader (which is hidden in Webpack config, hard to find if you just look at the code), although maybe that is too convenient to be removed, I'd leave it there. I am still not excited about using ids in component code, but that's from Foundation itself, I guess there is no choice
